name: Push to PyPI

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
      - name: Build the func_adl_servicex wheel
        env:
          func_adl_servicex_version: ${{ github.ref }}
        run: |
          python -m build --sdist --wheel
      - name: Publish func_adl_servicex to PyPI
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          user: __token__
          password: ${{ secrets.pypi_password_func_adl_servicex }}
